### PR TITLE
Change owner to root

### LINKED ISSUE #1: Binary should not belong user pirate
The docker-machine 0.7.0 DEB seems to have bug and creates the docker-machine binary owned by user pirate instead of user root.

Found that running our serverspec tests in image-builder-rpi repo.

```
rspec ./spec/hypriotos-image/docker-machine_spec.rb:16 # File "/usr/local/bin/docker-machine" should be owned by "root"
```

```
$ ls -l /usr/local/bin/docker-machine 
-rwxr-xr-x 1 pirate pirate 27152112 May 22 01:21 /usr/local/bin/docker-machine
```

### PR DESCRIPTION
**Pull request by StefanScherer**
Fixes #1

### CODE REVIEW

**Comment by StefanScherer** [comment]
DEB package built with fpm installs docker-machine as root:

```
$ ls -l /usr/local/bin/docker-machine 
-rwxr-xr-x 1 root root 27152112 May 24 06:46 /usr/local/bin/docker-machine
```

**Comment by StefanScherer** [comment]
fpm just works, calculates the size of the DEB (we once got 10GByte docker-machine 0.4.1 package) and fixes ownership of files etc.

@Govinda-Fichtner LGTY?

**Comment by Govinda-Fichtner** [comment]
@StefanScherer Well, I would say just go on. Saw that you tried it with 'chown' before. Will have a look at it later to see if I can make it work without fpm. Or we switch to fpm later for all our stuff. Just don't like to have to many different ways to do stuff without a real reason. That's all.

**Comment by StefanScherer** [comment]
Well, I prefer fpm 😄

**Pull request merged**
